debug: False
seed : 1771
path_to_files_base: "../data"
batch_size : 4
num_workers: 4
optimizer_lr: 0.006
optimizer_wd: 0
scheduler: "CosineAnnealingWarmRestarts"
model_name: "tf_efficientnet_b4"
metric : "custom"
loss_f: "nn.BCEWithLogitsLoss()"
optimizer: "Adam"
epochs: 5
